Some clean ups, fixes, config flag
trimental/inlyne pull request #91
Opened 2023-05-08 09:38 UTC by coastalwhite

This PR cleans up some aspects of the configuration management. It also implements #84. This also fixes the long form `page width` flag, which was previously broken.

2023-05-08 17:07 UTC, trimental commented
This changes look good to me. I'll let @CosmicHorrorDev give the final review since this mainly touches upon the code he has written.

2023-05-08 17:58 UTC, CosmicHorrorDev commented
I'll give it a look after I'm off work!

2023-05-08 23:43 UTC, CosmicHorrorDev requested changes
Just a few small nits, but otherwise looks great :+1:

This looks like three changes in a trenchcoat, so I'll address each in turn

---

**Fixing the broken page width flag**

Yikes, good find! I'll add a regression test to make sure that it actually gets tested for parsing in a follow-up PR

---

**Various cleanups**

I really appreciate all the changes. Everything seemed great to me!

---

**Adding a `--config` flag**

I see that this dropped modifying default values for `clap`'s help text with values from the config. Technically we _could_ still manage it by trying to parse args -> reading the config file -> actually parse the args, but a) I don't think that's worth the effort and b) I don't even think the original implementation before this PR was worth the effort. It gets a goodbye and good riddance from me :grin:

---

Overall I love the changes! Thanks for the PR

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/keybindings/defaults.rs
> +        };
I think I'd prefer something like `pub fn defaults() -> Vec<(Action, KeyCombo)>` in this file still and then

```rust
impl Default for Keybindings {
    fn default() -> Self {
        Self(defaults::defaults())
    }
}
```

in mod.rs just to try and keep impls contained in the same file

I definitely like making `Keybindings` into a proper type though!

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/keybindings/mod.rs
> +    #[inline]
```suggestion
```

Nit: Slapping `#[inline]` on functions without justifying through  something like checking the asm or benchmarks is generally a code smell. Chances are LLVM will already inline this and even if it doesn't this function isn't called nearly enough to be perf sensitive

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/opts/config.rs
> +        ))?;
```suggestion
        let config_content = read_to_string(path).context(format!(
            "Failed to read configuration file at '{}'",
            path.display(),
        ))?;
```

I think it's clearer to just use the typical interpolation style here

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/opts/mod.rs
> -        } = config;
I prefer destructuring all the values here as a way of future proofing that any additions to `Config` will be a hard compiler error here. Sure it's more code, but it also helps guide the programmer on what needs to be changed

It really should be done for `args` too. Not sure why I didn't

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/opts/cli.rs
> +    let page_width_arg = Arg::new("page width")
```suggestion
    let page_width_arg = Arg::new("page_width")
```

The arg reads a little awkward in the help text with the space in the center (`-w, --page-width <page width>`)

2023-05-08 23:43 UTC, CosmicHorrorDev commented on src/opts/cli.rs
> +        let page_width = matches.get_one("page width").cloned();
```suggestion
        let page_width = matches.get_one("page_width").cloned();
```

Other part of the last comment

2023-05-10 08:16 UTC, coastalwhite commented
I will have a look at this tonight

2023-05-10 17:44 UTC, CosmicHorrorDev commented
I'll take a look when I'm on my lunch break in about half an hour

2023-05-10 18:11 UTC, CosmicHorrorDev approved these changes
Thanks for all the changes, everything looks great!

2023-05-10 18:11 UTC, merged